name: Build Assets

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - run: npm install
      
      - run: npm run build
      
      - run: |
          git config --global user.name 'Simon Hamp'
          git config --global user.email 'simon.hamp@me.com'
          if git add dist/* ; then
            git commit -m "Build resources"
            git push
          fi
